development:
  adapter: mysql
  encoding: utf8
  database: ccomissao_development
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: ccomissao_test
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: ccomissao_production
  pool: 5
  username: root
  password: 
  host: localhost

